require 'pry'
require 'content_spinning'
require 'uri'
require 'json'
require 'net/http'
require 'openssl'
require 'time'
require 'faraday'
=begin
require 'html_to_plain_text'
require "RedCloth"
require 'cgi'
require 'httpclient'
require 'open-uri'
require 'date'
require 'rest-client'
require 'net/ssh'
require 'digest/md5'
require 'domainatrix'
=end
require_relative './functions'
require_relative './extend_string'
require_relative './extend_time'
require_relative './extend_datetime'
require_relative './extend_fixnum'
require_relative './extend_float'
require_relative './extend_exception'
